begin;

select plan(13);

select is(
  (
    select count(*)::integer
    from pg_proc
    join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
    where pg_namespace.nspname = 'public'
      and pg_proc.proname = 'accept_current_user_consent'
  ),
  1,
  'exactly one consent acceptance function exists'
);

select is(
  (
    select array_agg(policyname order by policyname)::text
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_consents'
  ),
  '{user_consents_select_own}',
  'user_consents has exactly the intended RLS policy'
);

select throws_ok(
  $$select * from public.accept_current_user_consent('2026-07-16:legal-disclosures-v2')$$,
  null,
  'Authentication required to accept consent.',
  'unauthenticated users cannot accept consent'
);

insert into auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
)
values
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'consent-a@example.com',
    'test-password',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'consent-b@example.com',
    'test-password',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  );

set local role authenticated;
select set_config('request.jwt.claim.sub', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', true);
select set_config('request.jwt.claim.role', 'authenticated', true);

select lives_ok(
  $$select * from public.accept_current_user_consent('2026-07-16:legal-disclosures-v2')$$,
  'authenticated users can accept consent'
);

reset role;

select is(
  (select version from public.user_consents where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
  '2026-07-16:legal-disclosures-v2',
  'accepted consent version is stored'
);

select isnt(
  (select accepted_at from public.user_consents where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
  null,
  'accepted consent timestamp is generated by the database'
);

select is(
  (select count(*)::integer from public.user_consents where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' and version = '2026-07-16:legal-disclosures-v2'),
  1,
  'one consent record exists per user and version'
);

update public.user_consents
set accepted_at = '2026-01-01 00:00:00+00'
where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
  and version = '2026-07-16:legal-disclosures-v2';

set local role authenticated;
select set_config('request.jwt.claim.sub', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
select * from public.accept_current_user_consent('2026-07-16:legal-disclosures-v2');

reset role;

select is(
  (select accepted_at from public.user_consents where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' and version = '2026-07-16:legal-disclosures-v2'),
  '2026-01-01 00:00:00+00'::timestamptz,
  'repeat acceptance preserves the original timestamp'
);

set local role authenticated;
select set_config('request.jwt.claim.sub', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
select * from public.accept_current_user_consent('2026-08-01:future-version');

reset role;

select is(
  (select count(*)::integer from public.user_consents where user_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
  2,
  'a new consent version creates a separate record'
);

set local role authenticated;
select set_config('request.jwt.claim.sub', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', true);
select set_config('request.jwt.claim.role', 'authenticated', true);

select is(
  (select count(*)::integer from public.user_consents),
  0,
  'cross-user consent records are hidden by RLS'
);

select throws_ok(
  $$insert into public.user_consents (user_id, version) values ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '2026-07-16:legal-disclosures-v2')$$,
  '42501',
  null,
  'clients cannot directly insert consent records'
);

select throws_ok(
  $$update public.user_consents set accepted_at = now() where user_id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'$$,
  '42501',
  null,
  'clients cannot update consent records'
);

select throws_ok(
  $$delete from public.user_consents where user_id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'$$,
  '42501',
  null,
  'clients cannot delete consent records'
);

reset role;

select * from finish();

rollback;
