"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/features/auth/lib/auth";
import type { WatchlistActionState, WatchlistItem } from "@/domain/watchlist";

function symbolFrom(data: FormData) { const value=String(data.get("symbol")??"").trim().toUpperCase(); if(!/^[A-Z0-9.-]{1,15}$/.test(value)) throw new Error("Symbol must contain 1–15 letters, numbers, dots, or hyphens."); return value; }
function idFrom(data: FormData) { const value=String(data.get("id")??""); if(!/^[0-9a-f-]{36}$/i.test(value)) throw new Error("Invalid watchlist item."); return value; }
export async function getWatchlistItems(): Promise<{items:WatchlistItem[];error?:string}> { const supabase=await createSupabaseServerClient(); const {data,error}=await supabase.from("watchlist_items").select("id, symbol, created_at").order("created_at",{ascending:false}).limit(25); if(error)return{items:[],error:"Watchlist could not be loaded."}; return{items:(data??[]).map((row:{id:string;symbol:string;created_at:string})=>({id:row.id,symbol:row.symbol,createdAt:row.created_at}))}; }
export async function addWatchlistItem(_:WatchlistActionState,data:FormData):Promise<WatchlistActionState>{try{const symbol=symbolFrom(data);const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{ok:false,message:"You must be signed in."};const {error}=await supabase.from("watchlist_items").insert({user_id:user.id,symbol});if(error)return{ok:false,message:error.code==="23505"?`${symbol} is already on your watchlist.`:"Item could not be saved."};revalidatePath("/watchlist");return{ok:true,message:`${symbol} added.`};}catch(error){return{ok:false,message:error instanceof Error?error.message:"Invalid symbol."};}}
export async function deleteWatchlistItem(_:WatchlistActionState,data:FormData):Promise<WatchlistActionState>{try{const id=idFrom(data);const supabase=await createSupabaseServerClient();const {error}=await supabase.from("watchlist_items").delete().eq("id",id);if(error)return{ok:false,message:"Item could not be removed."};revalidatePath("/watchlist");return{ok:true,message:"Item removed."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"Invalid item."};}}
